#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: pyproject
# autospec version: v3
# autospec commit: c1050fe
#
Name     : pypi-pydantic_core
Version  : 2.14.6
Release  : 4
URL      : https://files.pythonhosted.org/packages/b2/7d/8304d8471cfe4288f95a3065ebda56f9790d087edc356ad5bd83c89e2d79/pydantic_core-2.14.6.tar.gz
Source0  : https://files.pythonhosted.org/packages/b2/7d/8304d8471cfe4288f95a3065ebda56f9790d087edc356ad5bd83c89e2d79/pydantic_core-2.14.6.tar.gz
Source1  : http://localhost/cgit/vendor/pypi-pydantic_core/snapshot/pypi-pydantic_core-2023-11-28-00-55-39.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0 BSD-2-Clause BSL-1.0 ICU MIT Unicode-DFS-2016 Unlicense Zlib
Requires: pypi-pydantic_core-license = %{version}-%{release}
Requires: pypi-pydantic_core-python = %{version}-%{release}
Requires: pypi-pydantic_core-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(maturin)
BuildRequires : pypi(typing_extensions)
BuildRequires : pypi-maturin
BuildRequires : python3-staticdev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# pydantic-core
[![CI](https://github.com/pydantic/pydantic-core/workflows/ci/badge.svg?event=push)](https://github.com/pydantic/pydantic-core/actions?query=event%3Apush+branch%3Amain+workflow%3Aci)
[![Coverage](https://codecov.io/gh/pydantic/pydantic-core/branch/main/graph/badge.svg)](https://codecov.io/gh/pydantic/pydantic-core)
[![pypi](https://img.shields.io/pypi/v/pydantic-core.svg)](https://pypi.python.org/pypi/pydantic-core)
[![versions](https://img.shields.io/pypi/pyversions/pydantic-core.svg)](https://github.com/pydantic/pydantic-core)
[![license](https://img.shields.io/github/license/pydantic/pydantic-core.svg)](https://github.com/pydantic/pydantic-core/blob/main/LICENSE)

%package license
Summary: license components for the pypi-pydantic_core package.
Group: Default

%description license
license components for the pypi-pydantic_core package.


%package python
Summary: python components for the pypi-pydantic_core package.
Group: Default
Requires: pypi-pydantic_core-python3 = %{version}-%{release}

%description python
python components for the pypi-pydantic_core package.


%package python3
Summary: python3 components for the pypi-pydantic_core package.
Group: Default
Requires: python3-core
Provides: pypi(pydantic_core)
Requires: pypi(typing_extensions)

%description python3
python3 components for the pypi-pydantic_core package.


%prep
%setup -q -n pydantic_core-2.14.6
cd %{_builddir}
tar xf %{_sourcedir}/pypi-pydantic_core-2023-11-28-00-55-39.tar.xz
cd %{_builddir}/pydantic_core-2.14.6
mkdir -p ./vendor
cp -r %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/* %{_builddir}/pydantic_core-2.14.6/./vendor
mkdir -p .cargo
echo '[source.crates-io]' >> .cargo/config.toml
echo 'replace-with = "vendored-sources"' >> .cargo/config.toml
echo '[source.vendored-sources]' >> .cargo/config.toml
echo 'directory = "vendor"' >> .cargo/config.toml
pushd ..
cp -a pydantic_core-2.14.6 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1703782785
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation
pushd ../buildavx2/
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -m64 -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -m64 -march=x86-64-v3 "
python3 -m build --wheel --skip-dependency-check --no-isolation

popd

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-pydantic_core
cp %{_builddir}/pydantic_core-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/83ba7cc9eda2b15fee0037c3d7d3af32a290b6d1 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/ahash/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/ahash/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/2646b6d2453275031022ab245a3a6d5da4ba80b2 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/aho-corasick/COPYING %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/dd445710e6e4caccc4f8a587a130eaeebe83f6f6 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/aho-corasick/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/4c8990add9180fc59efa5b0d8faf643c9709501e || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/aho-corasick/UNLICENSE %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/ff007ce11f3ff7964f1a5b04202c4e95b5c82c85 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/autocfg/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/autocfg/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/e6d32072ef5f584a805b429ecbd4eec428316dde || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/base64/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/base64/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/b716916e6b0b96af5ecadf1eaee25f966f5d6cb2 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/bitflags/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/bitflags/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/cc/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/cc/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/3b042d3d971924ec0296687efd50dbe08b734976 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/cfg-if/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/cfg-if/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/3b042d3d971924ec0296687efd50dbe08b734976 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/enum_dispatch/LICENSE %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/5f899a092d7c9d00cfb6545f40da50942353b1ca || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/equivalent/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/equivalent/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/c371f0a7cbb203643d88566665a452f96bf1ab86 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/form_urlencoded/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/form_urlencoded/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/738188f5fed28a950b0fede659706238ec35f8bb || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/getrandom/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/e9b475b5dccf14bd66d72dd12a04db75eaad1a9e || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/getrandom/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/d74ad13f1402c35008f22bc588a6b8199ed164d3 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/hashbrown/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/hashbrown/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/c9c1c33aee599ebfdfb0bc2aed9ea082d9e3173a || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/heck/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/heck/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/60c3522081bf15d7ac1d4c5a63de425ef253e87a || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/idna/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/idna/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/a81399b7c3ec2d4619848fd59c11d21211fc3b86 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/indexmap/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/indexmap/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/7e5936a6fa3cf3518c01cec41345adf27399fe12 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/indoc/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/indoc/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/itoa/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/itoa/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/jiter/LICENSE %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/84ced1e5dac17ca675efc81ed06d4933bc2aadf7 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/lexical-core/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/5feaf15b3fa7d2d226d811e5fcd49098a1ea520c || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/lexical-core/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/lexical-core/LICENSE.md %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/3182da6e070c51dbe3d3148d1133e804598b07f2 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/lexical-parse-float/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/5feaf15b3fa7d2d226d811e5fcd49098a1ea520c || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/lexical-parse-float/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/lexical-parse-float/LICENSE.md %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/3182da6e070c51dbe3d3148d1133e804598b07f2 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/lexical-parse-integer/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/5feaf15b3fa7d2d226d811e5fcd49098a1ea520c || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/lexical-parse-integer/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/lexical-parse-integer/LICENSE.md %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/3182da6e070c51dbe3d3148d1133e804598b07f2 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/lexical-util/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/5feaf15b3fa7d2d226d811e5fcd49098a1ea520c || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/lexical-util/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/lexical-write-float/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/5feaf15b3fa7d2d226d811e5fcd49098a1ea520c || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/lexical-write-float/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/lexical-write-float/LICENSE.md %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/3182da6e070c51dbe3d3148d1133e804598b07f2 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/lexical-write-integer/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/5feaf15b3fa7d2d226d811e5fcd49098a1ea520c || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/lexical-write-integer/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/lexical-write-integer/LICENSE.md %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/3182da6e070c51dbe3d3148d1133e804598b07f2 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/libc/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/libc/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/36d69bcb88153a640740000efe933b009420ce7e || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/lock_api/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/lock_api/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/9a2b6b4ad55ec42cf19fc686c74668d3a6303ae7 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/memchr/COPYING %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/dd445710e6e4caccc4f8a587a130eaeebe83f6f6 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/memchr/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/4c8990add9180fc59efa5b0d8faf643c9709501e || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/memchr/UNLICENSE %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/ff007ce11f3ff7964f1a5b04202c4e95b5c82c85 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/memoffset/LICENSE %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/02bf11a87b9bbacedf2fcf4856af3b933faef82e || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/num-bigint/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/num-bigint/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/num-integer/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/num-integer/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/num-traits/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/num-traits/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/once_cell/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/once_cell/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/parking_lot/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/parking_lot/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/9a2b6b4ad55ec42cf19fc686c74668d3a6303ae7 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/parking_lot_core/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/parking_lot_core/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/9a2b6b4ad55ec42cf19fc686c74668d3a6303ae7 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/percent-encoding/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/percent-encoding/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/a81399b7c3ec2d4619848fd59c11d21211fc3b86 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/proc-macro2/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/proc-macro2/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/pyo3-build-config/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/5bb5828e544f63bd76c1b7112981a1ad86ae77f9 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/pyo3-build-config/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/959ce149b1615b8bff3437f59282396756987859 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/pyo3-ffi/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/5bb5828e544f63bd76c1b7112981a1ad86ae77f9 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/pyo3-ffi/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/959ce149b1615b8bff3437f59282396756987859 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/pyo3-macros-backend/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/5bb5828e544f63bd76c1b7112981a1ad86ae77f9 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/pyo3-macros-backend/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/959ce149b1615b8bff3437f59282396756987859 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/pyo3-macros/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/5bb5828e544f63bd76c1b7112981a1ad86ae77f9 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/pyo3-macros/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/959ce149b1615b8bff3437f59282396756987859 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/pyo3/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/5bb5828e544f63bd76c1b7112981a1ad86ae77f9 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/pyo3/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/959ce149b1615b8bff3437f59282396756987859 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/pyo3/pyo3-runtime/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/5bb5828e544f63bd76c1b7112981a1ad86ae77f9 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/pyo3/pyo3-runtime/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/959ce149b1615b8bff3437f59282396756987859 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/python3-dll-a/LICENSE %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/dc343e169fac680f93f90bc6cc63ca0c7a460131 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/quote/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/quote/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/redox_syscall/LICENSE %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/a00165152c82ea55b9fc254890dc8860c25e3bb6 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/regex-automata/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/regex-automata/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/regex-syntax/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/regex-syntax/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/regex-syntax/src/unicode_tables/LICENSE-UNICODE %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/68d12a03b339648117165b9c021b93f26974d6f6 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/regex/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/regex/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/rustversion/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/rustversion/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/ryu/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/ryu/LICENSE-BOOST %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/3cba29011be2b9d59f6204d6fa0a386b1b2dbd90 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/scopeguard/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/scopeguard/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/f498d95a48889a0b1432e420e6754881eff1d593 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/serde/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/serde/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/serde_derive/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/serde_derive/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/serde_json/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/serde_json/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/smallvec/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/smallvec/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/c61640f6c218caf86d1b8072e09668a8362dba04 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/speedate/LICENSE %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/83ba7cc9eda2b15fee0037c3d7d3af32a290b6d1 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/static_assertions/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/2b8b815229aa8a61e483fb4ba0588b8b6c491890 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/static_assertions/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/972723ef8f594b1c7515e4c227ff9d5912041fac || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/strum/LICENSE %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/967573fc64a706430e19b4942fe728870c8182f8 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/strum_macros/LICENSE %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/967573fc64a706430e19b4942fe728870c8182f8 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/syn/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/syn/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/target-lexicon/LICENSE %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/f137043e018f2024e0414a9153ea728c203ae8e5 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/tinyvec/LICENSE-APACHE.md %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/47b573e3824cd5e02a1a3ae99e2735b49e0256e4 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/tinyvec/LICENSE-MIT.md %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/ee70bf5efb387a6c52c0f5cbea4122c6a74a57bb || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/tinyvec/LICENSE-ZLIB.md %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/59b5efd50c4508e7fa74828e7469187bbe5bd864 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/tinyvec_macros/LICENSE-APACHE.md %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/8cc042e8e4b82c5532c72172a1988a74a599d4b5 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/tinyvec_macros/LICENSE-MIT.md %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/86d193cb6b24df990cbbaf67c6a24fddbcb574c1 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/unicode-bidi/COPYRIGHT %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/871b9912ab96cf7d79cb8ae83ca0b08cd5d0cbfd || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/unicode-bidi/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/unicode-bidi/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/60c3522081bf15d7ac1d4c5a63de425ef253e87a || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/unicode-ident/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/unicode-ident/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/unicode-ident/LICENSE-UNICODE %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/583a5eebcf6119730bd96922e8a0faecf7faf720 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/unicode-normalization/COPYRIGHT %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/5ed53061419caf64f84d064f3641392a2a10fa7f || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/unicode-normalization/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/unicode-normalization/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/60c3522081bf15d7ac1d4c5a63de425ef253e87a || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/unindent/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/unindent/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/url/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/url/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/a81399b7c3ec2d4619848fd59c11d21211fc3b86 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/uuid/COPYRIGHT %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/e5e5847604e0df7da8ec27a89a6a565bd1e84a91 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/uuid/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/uuid/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/459ceba57b368122a3cb1fd48edea59d1363cad7 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/version_check/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/version_check/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/cfcb552ef0afbe7ccb4128891c0de00685988a4b || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/wasi/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/wasi/LICENSE-Apache-2.0_WITH_LLVM-exception %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/f137043e018f2024e0414a9153ea728c203ae8e5 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/wasi/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/windows-targets/license-apache-2.0 %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/windows-targets/license-mit %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/windows_aarch64_gnullvm/license-apache-2.0 %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/windows_aarch64_gnullvm/license-mit %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/windows_aarch64_msvc/license-apache-2.0 %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/windows_aarch64_msvc/license-mit %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/windows_i686_gnu/license-apache-2.0 %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/windows_i686_gnu/license-mit %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/windows_i686_msvc/license-apache-2.0 %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/windows_i686_msvc/license-mit %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/windows_x86_64_gnu/license-apache-2.0 %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/windows_x86_64_gnu/license-mit %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/windows_x86_64_gnullvm/license-apache-2.0 %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/windows_x86_64_gnullvm/license-mit %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/windows_x86_64_msvc/license-apache-2.0 %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/windows_x86_64_msvc/license-mit %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/zerocopy-derive/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/ebbc0758a0322f1bfe28f5438867a084e53941c8 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/zerocopy-derive/LICENSE-BSD %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/46aace8adc5b06990d9ee2b6bd555ea03c4df7a1 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/zerocopy-derive/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/493b3ee6eb0b5b24708a0a07ab11ad2bc1b49c9c || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/zerocopy/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/ebbc0758a0322f1bfe28f5438867a084e53941c8 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/zerocopy/LICENSE-BSD %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/46aace8adc5b06990d9ee2b6bd555ea03c4df7a1 || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/zerocopy/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/493b3ee6eb0b5b24708a0a07ab11ad2bc1b49c9c || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/zerocopy/src/third_party/rust/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-pydantic_core-2023-11-28-00-55-39/zerocopy/src/third_party/rust/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-pydantic_core/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
python3 -m installer --destdir=%{buildroot} dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -m64 -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -m64 -march=x86-64-v3 "
python3 -m installer --destdir=%{buildroot}-v3 dist/*.whl
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-pydantic_core/02bf11a87b9bbacedf2fcf4856af3b933faef82e
/usr/share/package-licenses/pypi-pydantic_core/2646b6d2453275031022ab245a3a6d5da4ba80b2
/usr/share/package-licenses/pypi-pydantic_core/2b8b815229aa8a61e483fb4ba0588b8b6c491890
/usr/share/package-licenses/pypi-pydantic_core/3182da6e070c51dbe3d3148d1133e804598b07f2
/usr/share/package-licenses/pypi-pydantic_core/36d69bcb88153a640740000efe933b009420ce7e
/usr/share/package-licenses/pypi-pydantic_core/3b042d3d971924ec0296687efd50dbe08b734976
/usr/share/package-licenses/pypi-pydantic_core/3cba29011be2b9d59f6204d6fa0a386b1b2dbd90
/usr/share/package-licenses/pypi-pydantic_core/459ceba57b368122a3cb1fd48edea59d1363cad7
/usr/share/package-licenses/pypi-pydantic_core/46aace8adc5b06990d9ee2b6bd555ea03c4df7a1
/usr/share/package-licenses/pypi-pydantic_core/47b573e3824cd5e02a1a3ae99e2735b49e0256e4
/usr/share/package-licenses/pypi-pydantic_core/493b3ee6eb0b5b24708a0a07ab11ad2bc1b49c9c
/usr/share/package-licenses/pypi-pydantic_core/4c8990add9180fc59efa5b0d8faf643c9709501e
/usr/share/package-licenses/pypi-pydantic_core/5798832c31663cedc1618d18544d445da0295229
/usr/share/package-licenses/pypi-pydantic_core/583a5eebcf6119730bd96922e8a0faecf7faf720
/usr/share/package-licenses/pypi-pydantic_core/59b5efd50c4508e7fa74828e7469187bbe5bd864
/usr/share/package-licenses/pypi-pydantic_core/5bb5828e544f63bd76c1b7112981a1ad86ae77f9
/usr/share/package-licenses/pypi-pydantic_core/5ed53061419caf64f84d064f3641392a2a10fa7f
/usr/share/package-licenses/pypi-pydantic_core/5f899a092d7c9d00cfb6545f40da50942353b1ca
/usr/share/package-licenses/pypi-pydantic_core/5feaf15b3fa7d2d226d811e5fcd49098a1ea520c
/usr/share/package-licenses/pypi-pydantic_core/60c3522081bf15d7ac1d4c5a63de425ef253e87a
/usr/share/package-licenses/pypi-pydantic_core/689ec0681815ecc32bee639c68e7740add7bd301
/usr/share/package-licenses/pypi-pydantic_core/68d12a03b339648117165b9c021b93f26974d6f6
/usr/share/package-licenses/pypi-pydantic_core/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a
/usr/share/package-licenses/pypi-pydantic_core/738188f5fed28a950b0fede659706238ec35f8bb
/usr/share/package-licenses/pypi-pydantic_core/7e5936a6fa3cf3518c01cec41345adf27399fe12
/usr/share/package-licenses/pypi-pydantic_core/83ba7cc9eda2b15fee0037c3d7d3af32a290b6d1
/usr/share/package-licenses/pypi-pydantic_core/84ced1e5dac17ca675efc81ed06d4933bc2aadf7
/usr/share/package-licenses/pypi-pydantic_core/86d193cb6b24df990cbbaf67c6a24fddbcb574c1
/usr/share/package-licenses/pypi-pydantic_core/871b9912ab96cf7d79cb8ae83ca0b08cd5d0cbfd
/usr/share/package-licenses/pypi-pydantic_core/8cc042e8e4b82c5532c72172a1988a74a599d4b5
/usr/share/package-licenses/pypi-pydantic_core/959ce149b1615b8bff3437f59282396756987859
/usr/share/package-licenses/pypi-pydantic_core/967573fc64a706430e19b4942fe728870c8182f8
/usr/share/package-licenses/pypi-pydantic_core/972723ef8f594b1c7515e4c227ff9d5912041fac
/usr/share/package-licenses/pypi-pydantic_core/9a2b6b4ad55ec42cf19fc686c74668d3a6303ae7
/usr/share/package-licenses/pypi-pydantic_core/9f3c36d2b7d381d9cf382a00166f3fbd06783636
/usr/share/package-licenses/pypi-pydantic_core/a00165152c82ea55b9fc254890dc8860c25e3bb6
/usr/share/package-licenses/pypi-pydantic_core/a3b3a65335e78bde163f84d599fa899776552994
/usr/share/package-licenses/pypi-pydantic_core/a81399b7c3ec2d4619848fd59c11d21211fc3b86
/usr/share/package-licenses/pypi-pydantic_core/b716916e6b0b96af5ecadf1eaee25f966f5d6cb2
/usr/share/package-licenses/pypi-pydantic_core/c371f0a7cbb203643d88566665a452f96bf1ab86
/usr/share/package-licenses/pypi-pydantic_core/c61640f6c218caf86d1b8072e09668a8362dba04
/usr/share/package-licenses/pypi-pydantic_core/c9c1c33aee599ebfdfb0bc2aed9ea082d9e3173a
/usr/share/package-licenses/pypi-pydantic_core/ce3a2603094e799f42ce99c40941544dfcc5c4a5
/usr/share/package-licenses/pypi-pydantic_core/cfcb552ef0afbe7ccb4128891c0de00685988a4b
/usr/share/package-licenses/pypi-pydantic_core/d74ad13f1402c35008f22bc588a6b8199ed164d3
/usr/share/package-licenses/pypi-pydantic_core/dc343e169fac680f93f90bc6cc63ca0c7a460131
/usr/share/package-licenses/pypi-pydantic_core/dd445710e6e4caccc4f8a587a130eaeebe83f6f6
/usr/share/package-licenses/pypi-pydantic_core/e5e5847604e0df7da8ec27a89a6a565bd1e84a91
/usr/share/package-licenses/pypi-pydantic_core/e6d32072ef5f584a805b429ecbd4eec428316dde
/usr/share/package-licenses/pypi-pydantic_core/e9b475b5dccf14bd66d72dd12a04db75eaad1a9e
/usr/share/package-licenses/pypi-pydantic_core/ebbc0758a0322f1bfe28f5438867a084e53941c8
/usr/share/package-licenses/pypi-pydantic_core/ee70bf5efb387a6c52c0f5cbea4122c6a74a57bb
/usr/share/package-licenses/pypi-pydantic_core/f137043e018f2024e0414a9153ea728c203ae8e5
/usr/share/package-licenses/pypi-pydantic_core/f498d95a48889a0b1432e420e6754881eff1d593
/usr/share/package-licenses/pypi-pydantic_core/ff007ce11f3ff7964f1a5b04202c4e95b5c82c85

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/V3/usr/lib/python3*/*
/usr/lib/python3*/*
